"""widen dedup_key on reconciliation_entries

Revision ID: 1aaa1e11fa00
Revises: 5029ed073fdd
Create Date: 2026-07-22 10:58:05.916981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aaa1e11fa00'
down_revision: Union[str, None] = '5029ed073fdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reconciliation_entries', 'dedup_key',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=1500),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reconciliation_entries', 'dedup_key',
               existing_type=sa.String(length=1500),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
    # ### end Alembic commands ###
