"""add source file tracking to recon runs and reconciliation entries

Revision ID: 608a05551c8b
Revises: 3b55d5424768
Create Date: 2026-07-22 14:22:40.104216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '608a05551c8b'
down_revision: Union[str, None] = '3b55d5424768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default so this succeeds against existing rows in every real
    # environment (dev/staging/prod), not just an empty table.
    op.add_column(
        'recon_runs',
        sa.Column('bank_file_link', sa.String(length=1000), nullable=False, server_default=''),
    )
    op.add_column(
        'recon_runs',
        sa.Column('stripe_file_link', sa.String(length=1000), nullable=False, server_default=''),
    )
    op.add_column(
        'reconciliation_entries',
        sa.Column('source_file_name', sa.String(length=300), nullable=False, server_default=''),
    )
    op.add_column(
        'reconciliation_entries',
        sa.Column('source_file_link', sa.String(length=1000), nullable=False, server_default=''),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reconciliation_entries', 'source_file_link')
    op.drop_column('reconciliation_entries', 'source_file_name')
    op.drop_column('recon_runs', 'stripe_file_link')
    op.drop_column('recon_runs', 'bank_file_link')
    # ### end Alembic commands ###
